# Generated by Django 5.0.4 on 2024-04-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
